"""Add age, location, subcategory to detection

Revision ID: 2380795c459c
Revises: 
Create Date: 2026-03-04 10:34:20.385454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2380795c459c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('age', sa.String(), nullable=True))
    op.add_column('detection', sa.Column('location', sa.String(), nullable=True))
    op.add_column('detection', sa.Column('subcategory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection', 'subcategory')
    op.drop_column('detection', 'location')
    op.drop_column('detection', 'age')
    # ### end Alembic commands ###
