"""add_vehicle_fields

Revision ID: 25cd7ddd6ffd
Revises: 94be7134d662
Create Date: 2026-04-02 12:16:33.132979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25cd7ddd6ffd'
down_revision: Union[str, Sequence[str], None] = '94be7134d662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapondetection',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('weapon_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('camera_name', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapondetection_id'), 'weapondetection', ['id'], unique=False)
    op.add_column('detection', sa.Column('plate_number', sa.String(), nullable=True))
    op.add_column('detection', sa.Column('code', sa.String(), nullable=True))
    op.add_column('detection', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection', 'region')
    op.drop_column('detection', 'code')
    op.drop_column('detection', 'plate_number')
    op.drop_index(op.f('ix_weapondetection_id'), table_name='weapondetection')
    op.drop_table('weapondetection')
    # ### end Alembic commands ###
