"""Add eligible_for_assignment to Detection

Revision ID: 94be7134d662
Revises: ae523e81ed01
Create Date: 2026-03-26 16:25:57.265960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94be7134d662'
down_revision: Union[str, Sequence[str], None] = 'ae523e81ed01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('eligible_for_assignment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection', 'eligible_for_assignment')
    # ### end Alembic commands ###
