"""Add DetectionAssignment model

Revision ID: a281001e8b81
Revises: b16522185c2f
Create Date: 2026-04-16 15:30:37.505556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a281001e8b81'
down_revision: Union[str, Sequence[str], None] = 'b16522185c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detectionassignment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('distance_at_assignment', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('proof_urls', sa.JSON(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detectionassignment_id'), 'detectionassignment', ['id'], unique=False)
    op.drop_index(op.f('ix_trafficalert_id'), table_name='trafficalert')
    op.drop_table('trafficalert')
    op.add_column('detection', sa.Column('assignment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection', 'assignment_type')
    op.create_table('trafficalert',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('detection_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('officer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('proof_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], name=op.f('trafficalert_camera_id_fkey')),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], name=op.f('trafficalert_detection_id_fkey')),
    sa.ForeignKeyConstraint(['officer_id'], ['user.id'], name=op.f('trafficalert_officer_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('trafficalert_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trafficalert_pkey'))
    )
    op.create_index(op.f('ix_trafficalert_id'), 'trafficalert', ['id'], unique=False)
    op.drop_index(op.f('ix_detectionassignment_id'), table_name='detectionassignment')
    op.drop_table('detectionassignment')
    # ### end Alembic commands ###
