"""Change image_url to image_urls JSON

Revision ID: ae523e81ed01
Revises: 2380795c459c
Create Date: 2026-03-04 10:50:04.421501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae523e81ed01'
down_revision: Union[str, Sequence[str], None] = '2380795c459c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.drop_column('detection', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('detection', 'image_urls')
    # ### end Alembic commands ###
