"""Add allow_external_assignment to Detection

Revision ID: b16522185c2f
Revises: e38d0794ea67
Create Date: 2026-04-15 14:05:47.771307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16522185c2f'
down_revision: Union[str, Sequence[str], None] = 'e38d0794ea67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('allow_external_assignment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection', 'allow_external_assignment')
    # ### end Alembic commands ###
