"""Add expo_push_token to User

Revision ID: e38d0794ea67
Revises: 7e1722684da2
Create Date: 2026-04-15 12:08:34.039675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38d0794ea67'
down_revision: Union[str, Sequence[str], None] = '7e1722684da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('expo_push_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'expo_push_token')
    # ### end Alembic commands ###
