"""add company_type and linked_traffic_company_id

Revision ID: eda79288ed2b
Revises: 25cd7ddd6ffd
Create Date: 2026-04-09 09:46:27.914915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda79288ed2b'
down_revision: Union[str, Sequence[str], None] = '25cd7ddd6ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('linked_traffic_company_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'camera', 'organization', ['linked_traffic_company_id'], ['id'])
    op.add_column('organization', sa.Column('company_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'company_type')
    op.drop_constraint(None, 'camera', type_='foreignkey')
    op.drop_column('camera', 'linked_traffic_company_id')
    # ### end Alembic commands ###
